// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _api.Models;

#nullable disable

namespace _api.Migrations
{
    [DbContext(typeof(QlbanDtContext))]
    [Migration("20241206105644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_api.Models.Nguoidung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Anhdaidien")
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .IsFixedLength();

                    b.Property<string>("Diachi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dienthoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Idquyen")
                        .HasColumnType("int")
                        .HasColumnName("IDQuyen");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK_Nguoidung");

                    b.HasIndex("Idquyen");

                    b.ToTable("Nguoidung", (string)null);

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            Diachi = "Hà Nội",
                            Dienthoai = "0346715041",
                            Email = "sherryvippro@gmail.com",
                            Hoten = "Dương Thị Hằng",
                            Idquyen = 2,
                            Matkhau = "123456789"
                        },
                        new
                        {
                            MaNguoiDung = 2,
                            Diachi = "Thái Bình",
                            Dienthoai = "0938473021",
                            Email = "nvana@gmail.com",
                            Hoten = "Nguyễn Văn A",
                            Idquyen = 2,
                            Matkhau = "123409584"
                        },
                        new
                        {
                            MaNguoiDung = 3,
                            Diachi = "Hà Nội",
                            Dienthoai = "0346715041",
                            Email = "duongthia@gmail.com",
                            Hoten = "Dương Thị A",
                            Idquyen = 2,
                            Matkhau = "123456789"
                        },
                        new
                        {
                            MaNguoiDung = 4,
                            Diachi = "Hà Nội",
                            Dienthoai = "0346715041",
                            Email = "duongthib@gmail.com",
                            Hoten = "Dương Thị B",
                            Idquyen = 2,
                            Matkhau = "123456789"
                        },
                        new
                        {
                            MaNguoiDung = 5,
                            Diachi = "Hà Nội",
                            Dienthoai = "0346715041",
                            Email = "sherrie@gmail.com",
                            Hoten = "Dương Hằng",
                            Idquyen = 2,
                            Matkhau = "123456789"
                        });
                });

            modelBuilder.Entity("_api.Models.PhanQuyen", b =>
                {
                    b.Property<int>("Idquyen")
                        .HasColumnType("int")
                        .HasColumnName("IDQuyen");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idquyen");

                    b.ToTable("PhanQuyen", (string)null);

                    b.HasData(
                        new
                        {
                            Idquyen = 1,
                            TenQuyen = "Quản trị viên"
                        },
                        new
                        {
                            Idquyen = 2,
                            TenQuyen = "Khách hàng"
                        });
                });

            modelBuilder.Entity("_api.Models.TChiTietHdb", b =>
                {
                    b.Property<string>("SoHdb")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SoHDB");

                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<string>("KhuyenMai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Slban")
                        .HasColumnType("int")
                        .HasColumnName("SLBan");

                    b.Property<string>("ThanhTien")
                        .HasColumnType("integer");

                    b.HasKey("SoHdb", "MaSp");

                    b.HasIndex(new[] { "MaSp" }, "IX_tChiTietHDB");

                    b.ToTable("tChiTietHDB", (string)null);

                    b.HasData(
                        new
                        {
                            SoHdb = "HDB10000",
                            MaSp = "SP10000",
                            KhuyenMai = "0",
                            Slban = 5
                        },
                        new
                        {
                            SoHdb = "HDB10000",
                            MaSp = "SP10002",
                            KhuyenMai = "0",
                            Slban = 5
                        },
                        new
                        {
                            SoHdb = "HDB10001",
                            MaSp = "SP10002",
                            KhuyenMai = "0",
                            Slban = 5
                        },
                        new
                        {
                            SoHdb = "HDB10001",
                            MaSp = "SP10003",
                            KhuyenMai = "0",
                            Slban = 5
                        },
                        new
                        {
                            SoHdb = "HDB10002",
                            MaSp = "SP10003",
                            KhuyenMai = "0",
                            Slban = 5
                        });
                });

            modelBuilder.Entity("_api.Models.TChiTietHdn", b =>
                {
                    b.Property<string>("SoHdn")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SoHDN");

                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<string>("KhuyenMai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Slnhap")
                        .HasColumnType("int")
                        .HasColumnName("SLNhap");

                    b.HasKey("SoHdn", "MaSp");

                    b.HasIndex("MaSp");

                    b.ToTable("tChiTietHDN", (string)null);

                    b.HasData(
                        new
                        {
                            SoHdn = "HDN10000",
                            MaSp = "SP10000",
                            KhuyenMai = "0",
                            Slnhap = 50
                        },
                        new
                        {
                            SoHdn = "HDN10000",
                            MaSp = "SP10001",
                            KhuyenMai = "0",
                            Slnhap = 50
                        },
                        new
                        {
                            SoHdn = "HDN10000",
                            MaSp = "SP10002",
                            KhuyenMai = "0",
                            Slnhap = 50
                        },
                        new
                        {
                            SoHdn = "HDN10000",
                            MaSp = "SP10003",
                            KhuyenMai = "0",
                            Slnhap = 50
                        },
                        new
                        {
                            SoHdn = "HDN10001",
                            MaSp = "SP10004",
                            KhuyenMai = "0",
                            Slnhap = 50
                        });
                });

            modelBuilder.Entity("_api.Models.THang", b =>
                {
                    b.Property<string>("MaHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHang")
                        .HasName("PK_tTheLoai");

                    b.ToTable("tHang", (string)null);

                    b.HasData(
                        new
                        {
                            MaHang = "H01",
                            TenHang = "Apple"
                        },
                        new
                        {
                            MaHang = "H02",
                            TenHang = "Samsung"
                        },
                        new
                        {
                            MaHang = "H03",
                            TenHang = "Huawei"
                        },
                        new
                        {
                            MaHang = "H04",
                            TenHang = "Xiaomi"
                        },
                        new
                        {
                            MaHang = "H05",
                            TenHang = "Oppo"
                        });
                });

            modelBuilder.Entity("_api.Models.THoaDonBan", b =>
                {
                    b.Property<string>("SoHdb")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SoHDB");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBan")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TongHdb")
                        .HasColumnType("money")
                        .HasColumnName("TongHDB");

                    b.HasKey("SoHdb");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("tHoaDonBan", (string)null);

                    b.HasData(
                        new
                        {
                            SoHdb = "HDB10000",
                            MaNguoiDung = 1,
                            NgayBan = new DateTime(2024, 12, 6, 17, 56, 44, 93, DateTimeKind.Local).AddTicks(8424),
                            TongHdb = 0m
                        },
                        new
                        {
                            SoHdb = "HDB10001",
                            MaNguoiDung = 2,
                            NgayBan = new DateTime(2024, 12, 6, 17, 56, 44, 93, DateTimeKind.Local).AddTicks(8426),
                            TongHdb = 0m
                        },
                        new
                        {
                            SoHdb = "HDB10002",
                            MaNguoiDung = 3,
                            NgayBan = new DateTime(2024, 12, 6, 17, 56, 44, 93, DateTimeKind.Local).AddTicks(8427),
                            TongHdb = 0m
                        },
                        new
                        {
                            SoHdb = "HDB10003",
                            MaNguoiDung = 4,
                            NgayBan = new DateTime(2024, 12, 6, 17, 56, 44, 93, DateTimeKind.Local).AddTicks(8429),
                            TongHdb = 0m
                        },
                        new
                        {
                            SoHdb = "HDB10004",
                            MaNguoiDung = 5,
                            NgayBan = new DateTime(2024, 12, 6, 17, 56, 44, 93, DateTimeKind.Local).AddTicks(8430),
                            TongHdb = 0m
                        });
                });

            modelBuilder.Entity("_api.Models.THoaDonNhap", b =>
                {
                    b.Property<string>("SoHdn")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SoHDN");

                    b.Property<string>("MaNcc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TongHdn")
                        .HasColumnType("money")
                        .HasColumnName("TongHDN");

                    b.HasKey("SoHdn");

                    b.HasIndex("MaNcc");

                    b.ToTable("tHoaDonNhap", (string)null);

                    b.HasData(
                        new
                        {
                            SoHdn = "HDN10000",
                            MaNcc = "NCC01",
                            NgayNhap = new DateTime(2024, 12, 6, 17, 56, 44, 93, DateTimeKind.Local).AddTicks(8376),
                            TongHdn = 0m
                        },
                        new
                        {
                            SoHdn = "HDN10001",
                            MaNcc = "NCC02",
                            NgayNhap = new DateTime(2024, 12, 6, 17, 56, 44, 93, DateTimeKind.Local).AddTicks(8389),
                            TongHdn = 0m
                        },
                        new
                        {
                            SoHdn = "HDN10002",
                            MaNcc = "NCC02",
                            NgayNhap = new DateTime(2024, 12, 6, 17, 56, 44, 93, DateTimeKind.Local).AddTicks(8391),
                            TongHdn = 0m
                        },
                        new
                        {
                            SoHdn = "HDN10003",
                            MaNcc = "NCC03",
                            NgayNhap = new DateTime(2024, 12, 6, 17, 56, 44, 93, DateTimeKind.Local).AddTicks(8393),
                            TongHdn = 0m
                        },
                        new
                        {
                            SoHdn = "HDN10004",
                            MaNcc = "NCC04",
                            NgayNhap = new DateTime(2024, 12, 6, 17, 56, 44, 93, DateTimeKind.Local).AddTicks(8394),
                            TongHdn = 0m
                        });
                });

            modelBuilder.Entity("_api.Models.TNhaCungCap", b =>
                {
                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenNCC");

                    b.HasKey("MaNcc");

                    b.ToTable("tNhaCungCap", (string)null);

                    b.HasData(
                        new
                        {
                            MaNcc = "NCC01",
                            TenNcc = "Apple"
                        },
                        new
                        {
                            MaNcc = "NCC02",
                            TenNcc = "Samsung"
                        },
                        new
                        {
                            MaNcc = "NCC03",
                            TenNcc = "Huawei"
                        },
                        new
                        {
                            MaNcc = "NCC04",
                            TenNcc = "Xiaomi"
                        },
                        new
                        {
                            MaNcc = "NCC05",
                            TenNcc = "Oppo"
                        });
                });

            modelBuilder.Entity("_api.Models.TSp", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<string>("Anh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DonGiaBan")
                        .HasColumnType("money");

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("money");

                    b.Property<string>("MaHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaTl")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaTL");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK_tSach");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaTl");

                    b.ToTable("tSP", (string)null);

                    b.HasData(
                        new
                        {
                            MaSp = "SP10000",
                            DonGiaBan = 18000000m,
                            DonGiaNhap = 16000000m,
                            MaHang = "H01",
                            MaTl = "TL01",
                            SoLuong = 10,
                            TenSp = "iPhone 11 64GB | Chính hãng VN/A"
                        },
                        new
                        {
                            MaSp = "SP10001",
                            DonGiaBan = 20000000m,
                            DonGiaNhap = 18000000m,
                            MaHang = "H01",
                            MaTl = "TL01",
                            SoLuong = 10,
                            TenSp = "iPhone 11 128GB | Chính hãng VN/A"
                        },
                        new
                        {
                            MaSp = "SP10002",
                            DonGiaBan = 21000000m,
                            DonGiaNhap = 19000000m,
                            MaHang = "H01",
                            MaTl = "TL01",
                            SoLuong = 10,
                            TenSp = "iPhone 11 256GB | Chính hãng VN/A"
                        },
                        new
                        {
                            MaSp = "SP10003",
                            DonGiaBan = 23000000m,
                            DonGiaNhap = 20000000m,
                            MaHang = "H01",
                            MaTl = "TL01",
                            SoLuong = 10,
                            TenSp = "iPhone 11 Pro 256GB | Chính hãng VN/A"
                        },
                        new
                        {
                            MaSp = "SP10004",
                            DonGiaBan = 25000000m,
                            DonGiaNhap = 22000000m,
                            MaHang = "H01",
                            MaTl = "TL01",
                            SoLuong = 10,
                            TenSp = "iPhone 11 Pro Max 256GB | Chính hãng VN/A"
                        });
                });

            modelBuilder.Entity("_api.Models.TTheLoai", b =>
                {
                    b.Property<string>("MaTl")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaTL");

                    b.Property<string>("TenTl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTL");

                    b.HasKey("MaTl")
                        .HasName("PK_tNhaXuatBan");

                    b.ToTable("tTheLoai", (string)null);

                    b.HasData(
                        new
                        {
                            MaTl = "TL01",
                            TenTl = "Điện thoại"
                        },
                        new
                        {
                            MaTl = "TL02",
                            TenTl = "Laptop"
                        },
                        new
                        {
                            MaTl = "TL03",
                            TenTl = "Phụ kiện"
                        },
                        new
                        {
                            MaTl = "TL04",
                            TenTl = "Tivi"
                        },
                        new
                        {
                            MaTl = "TL05",
                            TenTl = "Đồng hồ"
                        });
                });

            modelBuilder.Entity("_api.Models.Nguoidung", b =>
                {
                    b.HasOne("_api.Models.PhanQuyen", "IdquyenNavigation")
                        .WithMany("Nguoidungs")
                        .HasForeignKey("Idquyen")
                        .IsRequired()
                        .HasConstraintName("FK_Nguoidung_PhanQuyen");

                    b.Navigation("IdquyenNavigation");
                });

            modelBuilder.Entity("_api.Models.TChiTietHdb", b =>
                {
                    b.HasOne("_api.Models.TSp", "MaSpNavigation")
                        .WithMany("TChiTietHdbs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_tChiTietHDB_tSP");

                    b.HasOne("_api.Models.THoaDonBan", "SoHdbNavigation")
                        .WithMany("TChiTietHdbs")
                        .HasForeignKey("SoHdb")
                        .IsRequired()
                        .HasConstraintName("FK_tChiTietHDB_tHoaDonBan");

                    b.Navigation("MaSpNavigation");

                    b.Navigation("SoHdbNavigation");
                });

            modelBuilder.Entity("_api.Models.TChiTietHdn", b =>
                {
                    b.HasOne("_api.Models.TSp", "MaSpNavigation")
                        .WithMany("TChiTietHdns")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_tChiTietHDN_tSP");

                    b.HasOne("_api.Models.THoaDonNhap", "SoHdnNavigation")
                        .WithMany("TChiTietHdns")
                        .HasForeignKey("SoHdn")
                        .IsRequired()
                        .HasConstraintName("FK_tChiTietHDN_tHoaDonNhap");

                    b.Navigation("MaSpNavigation");

                    b.Navigation("SoHdnNavigation");
                });

            modelBuilder.Entity("_api.Models.THoaDonBan", b =>
                {
                    b.HasOne("_api.Models.Nguoidung", "MaNguoiDungNavigation")
                        .WithMany("THoaDonBans")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_tHoaDonBan_Nguoidung");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("_api.Models.THoaDonNhap", b =>
                {
                    b.HasOne("_api.Models.TNhaCungCap", "MaNccNavigation")
                        .WithMany("THoaDonNhaps")
                        .HasForeignKey("MaNcc")
                        .IsRequired()
                        .HasConstraintName("FK_tHoaDonNhap_tNhaCungCap");

                    b.Navigation("MaNccNavigation");
                });

            modelBuilder.Entity("_api.Models.TSp", b =>
                {
                    b.HasOne("_api.Models.THang", "MaHangNavigation")
                        .WithMany("TSp")
                        .HasForeignKey("MaHang")
                        .IsRequired()
                        .HasConstraintName("FK_tSP_tHang");

                    b.HasOne("_api.Models.TTheLoai", "MaTlNavigation")
                        .WithMany("TSp")
                        .HasForeignKey("MaTl")
                        .IsRequired()
                        .HasConstraintName("FK_tSP_tTheLoai");

                    b.Navigation("MaHangNavigation");

                    b.Navigation("MaTlNavigation");
                });

            modelBuilder.Entity("_api.Models.Nguoidung", b =>
                {
                    b.Navigation("THoaDonBans");
                });

            modelBuilder.Entity("_api.Models.PhanQuyen", b =>
                {
                    b.Navigation("Nguoidungs");
                });

            modelBuilder.Entity("_api.Models.THang", b =>
                {
                    b.Navigation("TSp");
                });

            modelBuilder.Entity("_api.Models.THoaDonBan", b =>
                {
                    b.Navigation("TChiTietHdbs");
                });

            modelBuilder.Entity("_api.Models.THoaDonNhap", b =>
                {
                    b.Navigation("TChiTietHdns");
                });

            modelBuilder.Entity("_api.Models.TNhaCungCap", b =>
                {
                    b.Navigation("THoaDonNhaps");
                });

            modelBuilder.Entity("_api.Models.TSp", b =>
                {
                    b.Navigation("TChiTietHdbs");

                    b.Navigation("TChiTietHdns");
                });

            modelBuilder.Entity("_api.Models.TTheLoai", b =>
                {
                    b.Navigation("TSp");
                });
#pragma warning restore 612, 618
        }
    }
}
